---
language: python
python: "2.7"

env:
  - SITE=test.yml

notifications:
  slack:
    secure: "HaP5VCMXZOXuvyjwhwE7HzsBjI/yxO9cbzBPt6kWwNBUEHlydfsJyl+7xKtU4r+/xfFtQGnI5oDyeK6cMRdoje/iM6RBRbbFy+TlOQ8U3l2rx0euePYfyRt6m1PkGDyummxkcFLmGAZo9vRW3rgCZGkd69dW4nHulPW3taLYn/A="

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install curl
  # Avoid harmless (but annoying) warnings.
  - mkdir ~/.python-eggs
  - chmod 700 ~/.python-eggs

script:
  - "curl https://raw.githubusercontent.com/GetValkyrie/ansible-bootstrap/master/install-ansible.sh|sudo /bin/sh"
  # Check that expected executables are available
  - "which ansible"
  - "ansible -h| grep \"Usage: ansible\""
  - "which ansible-playbook"
  - "ansible-playbook -h| grep \"Usage: ansible-playbook\""
  - "which ansible-galaxy"
  - "ansible-galaxy -h| grep \"Usage: ansible-galaxy\""
